services:
  vrisa_db:
    image: postgres:15
    environment:
      POSTGRES_DB: vrisa_db
      POSTGRES_USER: vrisa_user
      POSTGRES_PASSWORD: local_password_1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    image: vrisa-backend:1.0.0
    build: .
    container_name: vrisa_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=vrisa_db
      - POSTGRES_USER=vrisa_user
      - POSTGRES_PASSWORD=local_password_1234
      - POSTGRES_HOST=vrisa_db
    depends_on:
      - vrisa_db
  
  simulator:
    image: vrisa-backend:1.0.0
    container_name: vrisa_simulator
    command: python manage.py start_simulation
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=vrisa_db
      - POSTGRES_USER=vrisa_user
      - POSTGRES_PASSWORD=local_password_1234
      - POSTGRES_HOST=vrisa_db
    depends_on:
      - vrisa_db
      - backend

volumes:
  pgdata:
